# App-specific tweaks
source = ~/.local/share/latiarch/default/hypr/apps/bitwarden.conf
source = ~/.local/share/latiarch/default/hypr/apps/browser.conf
source = ~/.local/share/latiarch/default/hypr/apps/hyprshot.conf
source = ~/.local/share/latiarch/default/hypr/apps/jetbrains.conf
source = ~/.local/share/latiarch/default/hypr/apps/pip.conf
source = ~/.local/share/latiarch/default/hypr/apps/qemu.conf
source = ~/.local/share/latiarch/default/hypr/apps/retroarch.conf
source = ~/.local/share/latiarch/default/hypr/apps/steam.conf
source = ~/.local/share/latiarch/default/hypr/apps/system.conf
source = ~/.local/share/latiarch/default/hypr/apps/terminals.conf
