# All the default LatiArch aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/latiarch/default/zsh/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:/home/burkii/.spicetify

# add Pulumi to the PATH
export PATH=$PATH:/home/burkii/.pulumi/bin

# aliases
alias awsls="LS_LOG=trace localstack start"
alias vimcheat="cat ~/.vim-cheat.txt"
alias termcheat="ghostty +list-keybinds --default"
