# All the default LatiArch aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/latiarch/default/zsh/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
